// FORGOT_PASS types
 
export const FORGOT_PASS_FETCH_REQUEST = 'FORGOT_PASS_FETCH_REQUEST';
export const FORGOT_PASS_FETCH_SUCCESS = 'FORGOT_PASS_FETCH_SUCCESS';
export const FORGOT_PASS_FETCH_FAIL = 'FORGOT_PASS_FETCH_FAIL';
