const TAG = 'LOGIN_'
export const UPDATE_ACCESS_TOKEN = TAG + 'UPDATE_ACCESS_TOKEN';
export const API_LOADING_START = TAG + 'API_LOADING_START';
export const API_LOADING_STOP = TAG + 'API_LOADING_STOP';


// Login 
export const LOGIN_FETCH_REQUEST = 'LOGIN_FETCH_REQUEST';
export const LOGIN_FETCH_SUCCESS = 'LOGIN_FETCH_SUCCESS';
export const LOGIN_FETCH_FAIL = 'LOGIN_FETCH_FAIL';

