// News 
export const NEWSDETAIL_FETCH_REQUEST = 'NEWSDETAIL_FETCH_REQUEST';
export const NEWSDETAIL_FETCH_SUCCESS = 'NEWSDETAIL_FETCH_SUCCESS';
export const NEWSDETAIL_FETCH_FAIL = 'NEWSDETAIL_FETCH_FAIL';