// TRAINING_SCHEDULE types
 
export const TRAINING_SCHEDULE_FETCH_REQUEST = 'TRAINING_SCHEDULE_FETCH_REQUEST';
export const TRAINING_SCHEDULE_FETCH_SUCCESS = 'TRAINING_SCHEDULE_FETCH_SUCCESS';
export const TRAINING_SCHEDULE_FETCH_FAIL = 'TRAINING_SCHEDULE_FETCH_FAIL';
