// TRAINING_ASSESMENT types
 
export const TRAINING_ASSESMENT_FETCH_REQUEST = 'TRAINING_ASSESMENT_FETCH_REQUEST';
export const TRAINING_ASSESMENT_FETCH_SUCCESS = 'TRAINING_ASSESMENT_FETCH_SUCCESS';
export const TRAINING_ASSESMENT_FETCH_FAIL = 'TRAINING_ASSESMENT_FETCH_FAIL';
