// FLOORMAP types
 
export const FLOORMAP_FETCH_REQUEST = 'FLOORMAP_FETCH_REQUEST';
export const FLOORMAP_FETCH_SUCCESS = 'FLOORMAP_FETCH_SUCCESS';
export const FLOORMAP_FETCH_FAIL = 'FLOORMAP_FETCH_FAIL';
