// SEND_MAIL types
 
export const SEND_MAIL_FETCH_REQUEST = 'SEND_MAIL_FETCH_REQUEST';
export const SEND_MAIL_FETCH_SUCCESS = 'SEND_MAIL_FETCH_SUCCESS';
export const SEND_MAIL_FETCH_FAIL = 'SEND_MAIL_FETCH_FAIL';
