// TRAINING_SCAN types
 
export const TRAINING_SCAN_FETCH_REQUEST = 'TRAINING_SCAN_FETCH_REQUEST';
export const TRAINING_SCAN_FETCH_SUCCESS = 'TRAINING_SCAN_FETCH_SUCCESS';
export const TRAINING_SCAN_FETCH_FAIL = 'TRAINING_SCAN_FETCH_FAIL';
