// ANSWER_SUBMIT 
export const ANSWER_SUBMIT_FETCH_REQUEST = 'ANSWER_SUBMIT_FETCH_REQUEST';
export const ANSWER_SUBMIT_FETCH_SUCCESS = 'ANSWER_SUBMIT_FETCH_SUCCESS';
export const ANSWER_SUBMIT_FETCH_FAIL = 'ANSWER_SUBMIT_FETCH_FAIL';