// BREAKFAST 
export const BREAKFAST_FETCH_REQUEST = 'BREAKFAST_FETCH_REQUEST';
export const BREAKFAST_FETCH_SUCCESS = 'BREAKFAST_FETCH_SUCCESS';
export const BREAKFAST_FETCH_FAIL = 'BREAKFAST_FETCH_FAIL';