// FEDDBACK_QUESTION types
 
export const FEDDBACK_QUESTION_FETCH_REQUEST = 'FEDDBACK_QUESTION_FETCH_REQUEST';
export const FEDDBACK_QUESTION_FETCH_SUCCESS = 'FEDDBACK_QUESTION_FETCH_SUCCESS';
export const FEDDBACK_QUESTION_FETCH_FAIL = 'FEDDBACK_QUESTION_FETCH_FAIL';
