// REFERENCES types
 
export const REFERENCES_FETCH_REQUEST = 'REFERENCES_FETCH_REQUEST';
export const REFERENCES_FETCH_SUCCESS = 'REFERENCES_FETCH_SUCCESS';
export const REFERENCES_FETCH_FAIL = 'REFERENCES_FETCH_FAIL';
