// BEVERAGES 
export const BEVERAGES_FETCH_REQUEST = 'BEVERAGES_FETCH_REQUEST';
export const BEVERAGES_FETCH_SUCCESS = 'BEVERAGES_FETCH_SUCCESS';
export const BEVERAGES_FETCH_FAIL = 'BEVERAGES_FETCH_FAIL';