// BUILD_VERSION types
 
export const BUILD_VERSION_FETCH_REQUEST = 'BUILD_VERSION_FETCH_REQUEST';
export const BUILD_VERSION_FETCH_SUCCESS = 'BUILD_VERSION_FETCH_SUCCESS';
export const BUILD_VERSION_FETCH_FAIL = 'BUILD_VERSION_FETCH_FAIL';
