// USER_FEEDBACK types
 
export const USER_FEEDBACK_FETCH_REQUEST = 'USER_FEEDBACK_FETCH_REQUEST';
export const USER_FEEDBACK_FETCH_SUCCESS = 'USER_FEEDBACK_FETCH_SUCCESS';
export const USER_FEEDBACK_FETCH_FAIL = 'USER_FEEDBACK_FETCH_FAIL';
