// MYSCHEDULES_LIST types
 
export const MYSCHEDULES_LIST_FETCH_REQUEST = 'MYSCHEDULES_LIST_FETCH_REQUEST';
export const MYSCHEDULES_LIST_FETCH_SUCCESS = 'MYSCHEDULES_LIST_FETCH_SUCCESS';
export const MYSCHEDULES_LIST_FETCH_FAIL = 'MYSCHEDULES_LIST_FETCH_FAIL';
