// MYTRAINING_LIST types
 
export const MYTRAINING_LIST_FETCH_REQUEST = 'MYTRAINING_LIST_FETCH_REQUEST';
export const MYTRAINING_LIST_FETCH_SUCCESS = 'MYTRAINING_LIST_FETCH_SUCCESS';
export const MYTRAINING_LIST_FETCH_FAIL = 'MYTRAINING_LIST_FETCH_FAIL';
