// REGISTER_QUERY types
 
export const REGISTER_QUERY_FETCH_REQUEST = 'REGISTER_QUERY_FETCH_REQUEST';
export const REGISTER_QUERY_FETCH_SUCCESS = 'REGISTER_QUERY_FETCH_SUCCESS';
export const REGISTER_QUERY_FETCH_FAIL = 'REGISTER_QUERY_FETCH_FAIL';
