// VENDOR_LIST types
 
export const VENDOR_LIST_FETCH_REQUEST = 'VENDOR_LIST_FETCH_REQUEST';
export const VENDOR_LIST_FETCH_SUCCESS = 'VENDOR_LIST_FETCH_SUCCESS';
export const VENDOR_LIST_FETCH_FAIL = 'VENDOR_LIST_FETCH_FAIL';
