// CHANGE_PASSWORD 
export const CHANGE_PASSWORD_FETCH_REQUEST = 'CHANGE_PASSWORD_FETCH_REQUEST';
export const CHANGE_PASSWORD_FETCH_SUCCESS = 'CHANGE_PASSWORD_FETCH_SUCCESS';
export const CHANGE_PASSWORD_FETCH_FAIL = 'CHANGE_PASSWORD_FETCH_FAIL';