// FEEDBACK types
 
export const FEEDBACK_FETCH_REQUEST = 'FEEDBACK_FETCH_REQUEST';
export const FEEDBACK_FETCH_SUCCESS = 'FEEDBACK_FETCH_SUCCESS';
export const FEEDBACK_FETCH_FAIL = 'FEEDBACK_FETCH_FAIL';
